### ISSUE TITLE
Vertex ID in URP_PBRLitTemplate

### ISSUE THREAD

**Issue by Mdlich** [Cyanilux/URP_ShaderCodeTemplates#1]
Hello there!
I am trying to get the vertex id in the vertex shader, however no matter what I'm doing, it seems to always be 0. Do you happen to know how to get it properly? I'm gonna try it in a simple unlit shader as well to see if it's related to unity macros.

**Comment by Cyanilux** [comment]
To obtain the vertex ID you should only need to add `uint vertexID : SV_VertexID;` to the vertex input struct (Attributes), (or as an additional parameter to the vertex program function). I've tested it in the unlit one by adjusting the color based on it (e.g. `OUT.color = IN.vertexID / 515.0;`) and the result is definitely non-zero.

**Comment by Mdlich** [comment]
> To obtain the vertex ID you should only need to add `uint vertexID : SV_VertexID;` to the vertex input struct (Attributes), (or as an additional parameter to the vertex program function). I've tested it in the unlit one by adjusting the color based on it (e.g. `OUT.color = IN.vertexID / 515.0;`) and the result is definitely non-zero.

Thank you for your quick reply! Upon further testing I found out that indeed the problem was not with the vertex ids, but rather with structured buffers that I provided to the shader.
